### ISSUE TITLE
Can not find labels.csv and age.csv

### ISSUE THREAD

**Issue by MitraDarja** [mdanb/aging_rna_seq_metaanalysis#1]
Hi,

I think your project is really interesting and I am trying to understand better what you have done, by doing so I noticed I can not find the following files:  labels.csv and age.csv, which should be in ../common_datastore, but I can not find the directory?

Am I blind? :)

Best wishes,
Mitradarja

**Comment by mdanb** [comment]
Hi Mitradarja,

Thank you for your interest in the project :) 

Were you looking in the Docker container or on Github? `common_datastore` is not on Github because it's large. 

Please let me know if you still can't find it!

**Comment by MitraDarja** [comment]
Thanks for your fast response. 
I had not checked the docker, I have found it now. :)

**Comment by paulmenzel** [comment]
`age.csv` and `labels.csv` are only 16 kB in size. ;-)

@mdanb, I recommend to ask your IT department if they offer ways to host such data.

**Comment by mdanb** [comment]
@paulmenzel yeah I could have just uploaded those tbh on Github, it's just the way we decided to host the data was just to put everything that was originally in `common_datastore` on Docker.
